---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: todo-app
spec:
  selector:
    matchLabels:
      app: todo-app
  template:
    metadata:
      labels:
        app: todo-app
        role: business-logic
    spec:
      containers:
        - name: todo-app
          image: ghcr.io/hamidreza-ygh8/tenant-software/todo-app:latest #x-release-please-version
          # resources:
          #   requests:
          #     memory: "32Mi"
          #     cpu: "100m"
          #   limits:
          #     memory: "128Mi"
          #     cpu: "500m"
          ports:
            - name: http
              containerPort: 8000
              protocol: TCP
          # livenessProbe:
          #   httpGet:
          #     path: /healthz
          #     port: http
          # readinessProbe:
          #   httpGet:
          #     path: /readyz
          #     port: http

---
apiVersion: v1
kind: Service
metadata:
  name: todo-app
spec:
  selector:
    app: todo-app
  ports:
    - name: http
      port: 8000
      protocol: TCP
  type: ClusterIP